#!/bin/bash

exec 6<&0
exec 0<output.txt
count=1

while read line
do 
	echo "Line #$count: $line"
	count=$[ $count + 1 ]
done 
exec 0<&6

read -p "Are you done now? " answer
case $answer in 
Y|y) echo "Good bye";;
N|n) echo "but I am done";;
esac

