#!/bin/bash

temp=$(mktemp test.XXXXXXX)
exec 3>&$temp

echo "this file writes to a tmp file $temp"

echo "This is the first line" >&3
echo "This is the second line." >&3
echo "This is the last line." >&3
exec 3>&-

echo "Done creating temp file. The contents are: "
cat $tempfile
rm -f $temp 2> /dev/null
ls -al test*
