#!/bin/bash
# Testing the test command
#
my_variable="yes"
#
if test $my_variable
then
echo "The $my_variable expression returns a True"
#
else
echo "The $my_variable expression returns a False"
fi

my_variable=""
#
if test $my_variable
then
echo "The $my_variable expression returns a True"
#
else
echo "The $my_variable expression returns a False"
fi

#alternate method

value1=10
value2=11

if [ $value1 -gt 5 ]     #note the space after first bracket and before last bracket are mandatory.
then	
	echo $value1 is greater than 5
fi

if [ $value1 -eq $value2 ]
then 
	echo $value1 is equal to $value2
else
	echo $value1 is not equal to $value2
fi



